# This is a basic workflow to help you get started with Actions

name: Aprendiendo Github Actions #Nombre del workflow #Opcional
run-name: ¡Estoy aprendiendo Github Actions! #Este se muestra en el eevnto o run del workflow #Opcional
on: [push] #evento que lo activará

jobs: #Definición de los jobs
  hola-mundo: #Nombre del job
    runs-on: ubuntu-latest #Maquina en la que correrá

    steps: #Lista de steps del job hola-mundo
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4 # Aquí es donde realmente usas 'with'
        with:
          node-version: 18

      - name: Definir variable
        run: echo "USERNAME=${{github.actor}}" >> $GITHUB_ENV

      # - name: Instalar dependencias
      #   run: npm install

      - name: Correr script #Nombre del step
        run: node index.js
