name: Mostrando-secretos
run-name: ¡estoy aprendiendo secretos!

on: 
    push:
        branches: [main]

jobs:
    Deploy-Secret:
        runs-on: ubuntu-latest
        steps:
            - name: correr y mostrar variable
              run: echo Hola ${{vars.VARIABLEDEMO}}

            - name: Correr y mostrar secretos
              run: echo ${{ secrets.GITHUB_TOKEN }} y ${{secrets.MISECRETO}}


